# This file is a template and might need editing before use.
# Full project: https://gitlab.com/pages/plain-html

image: alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Deploying site to $CI_PAGES_URL"
    - mkdir -p public
    - cp -r * public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Deploy only on default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # Allow on merge requests
    - if: $CI_COMMIT_TAG  # Allow tagged releases
